---
- name: Clear old log files
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Find log files older than 10 days
      find:
        paths: /var/log
        patterns: "*.log"
        age: "10d"
      register: log_files

    - name: Remove old log files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ log_files.files }}"
